
---
spring:
  jpa:
    generate-ddl: true
 
#US Region  
mongodb:
    testmessage: hello
    mongoNodes:
        - host: 104.42.196.109
          port: 27017
                   
    mongoNodeCredentials:
        - username: admin
          password: password
          authSource: admin